name = "personal-website"
main = "index.js"
pages_build_output_dir = "."
compatibility_date = "2025-01-01"

[assets]
directory = "."

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "personal-website-db"
database_id = "95fb9a3b-ea01-4fca-8df8-f6a1a4662045"
